name: Frontend Check

on:
  pull_request:
    paths:
      - './**'
      - '!contract_/**'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  build-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - name: Print PATH before pnpm setup (for debugging)
        run: echo "PATH before pnpm setup: $PATH"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Print PATH after pnpm setup (for debugging)
        run: echo "PATH after pnpm setup: $PATH"

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install pnpm using npm (fallback if pnpm/action-setup fails)
        if: failure()
        run: npm install -g pnpm@8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
