name: Frontend Check

on:
  pull_request:
    paths:
      - './**'
      - '!contract_/**' 
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  build-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml' 

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build